# Generated by Django 5.2.8 on 2025-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_full',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_short',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/', verbose_name='Изображение'),
        ),
    ]
