# Generated by Django 5.2.8 on 2025-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает в'),
        ),
    ]
